
-- BOARD 삭제
DROP TABLE BOARD

-- BOARD 테이블 생성
CREATE TABLE BOARD(
	BNO NUMBER(38) PRIMARY KEY
--	, BNAME VARCHAR2(100)
	, BTITLE VARCHAR2(200)
--	, BPWD VARCHAR2(20)
	, BCONT VARCHAR2(4000)
	, BHIT NUMBER(38) DEFAULT 0
	, BDATE DATE 
	);

SELECT * FROM BOARD

-- BNOSEQ 시퀀스 생성
CREATE SEQUENCE BNOSEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 시퀀스 값 확인
SELECT BNOSEQ.NEXTVAL FROM DUAL;
-- 시퀀스명.NEXTVAL을 사용하면 현재 이후 번호값을 발생해서 확인가능함.

--GUEST 테이블에 3개 레코드행 저장 실습
INSERT INTO BOARD (BNO, BNAME, BTITLE, BPWD, BCONT, BDATE)
VALUES(MNOSEQ.NEXTVAL, '홍길동', '제목01', '7777', '내용01', SYSDATE);

INSERT INTO BOARD (MNO, MNAME, MTITLE, MPWD, MCONT, MDATE)
VALUES(MNOSEQ.NEXTVAL, '이순신', '제목01', '8888', '내용01', SYSDATE);

INSERT INTO BOARD (MNO, MNAME, MTITLE, MPWD, MCONT, MDATE)
VALUES(MNOSEQ.NEXTVAL, '강감찬', '제목02', '9999', '내용02', SYSDATE);

INSERT INTO BOARD (BNO, BTITLE, BCONT, BDATE) VALUES (BNOSEQ.NEXTVAL, '제목', '내용', SYSDATE)

--번호를 기준으로 내림차순 정렬
SELECT * FROM BOARD ORDER BY BNO DESC;

--DELETE * FROM INDIGUEST

SELECT * FROM BOARD WHERE BNO = 360
